version: "3"
services:
  frontend:
    build: php-mariadb
    volumes:
      - ./src:/var/www/html
    ports:
      - 8765:80
    environment:
      - MARIADB_DATABASE=sample
      - MARIADB_USER=user
      - MARIADB_PASSWORD=pass
      
  backend:
    image: densukest/mariadb-jp

    volumes:
      - ./initdb:/docker-entrypoint-initdb.d


